### ISSUE TITLE
System Requirements 

### ISSUE THREAD

**Issue by INF800** [3DTopia/3DTopia#2]
Hi, can you please add system requirements in the README.md file?

**Comment by INF800** [comment]
Can we run this in Kaggle or Colab

**Comment by hongfz16** [comment]
Thank you for the suggestion. For the first stage, the minimum GPU requirement is RTX 2080ti. The second stage is recommended to run on at least V100.

**Comment by hayoung-jeremy** [comment]
Hi, I'm trying to run it on an A10 GPU cloud instance from LambdaCloud, is it okay for the second stage though?
