### ISSUE TITLE
Stable Diffusion Version Used

### ISSUE THREAD

**Issue by adeerAI** [3DTopia/3DTopia#4]
Hi there,

I wanted to ask which Stable Diffusion version is being used by 3dTopia and that can I use a safetensor file type as checkpoint instead of downloading the mentioned one in the Readme file.

Regards

**Comment by hongfz16** [comment]
I believe our code is based on [Stable Diffusion v1](https://github.com/CompVis/stable-diffusion). Thank you for the suggestion of using safetensors. We will consider switching to that in the future.
