### ISSUE TITLE
[Kaggle] Dependency installation for stage2 not working.

### ISSUE THREAD

**Issue by INF800** [3DTopia/3DTopia#5]
I got stage 1 working with the following output:

https://github.com/3DTopia/3DTopia/assets/45640029/cb66040c-9850-444c-bceb-fd15d73f40bf

However, dependencies for stage 2 were not installed correctly.

Link to notebook (with errors): https://www.kaggle.com/code/l0new0lf/3dtopia?scriptVersionId=160258957

**Comment by INF800** [comment]
Maybe the solution is to deactivate the environment, start a new
environment and do installation.

**Comment by hongfz16** [comment]
Hi all. Thank you for trying out our repo. I have been testing our environment on different machines and have no problem. The stage2 can be installed together with stage1 with torch=1.12.0 and cuda=11.3.

@INF800 I have not tried with kaggle or colab machines. But stage2 involves many cuda kernel compilation, which might not be supported well by these platforms.
